---
language: python
python: "2.7"

sudo: required
dist: trusty

# Install ansible
addons:
  apt:
    packages:
    - python-pip

before_install:
  - sudo apt-get update -qq

  # upgrade libpcre3 (see https://github.com/oerdnj/deb.sury.org/issues/755)
  - sudo add-apt-repository -y ppa:ondrej/php
  - sudo apt-get install libpcre3 libpcre16-3 libpcre32-3 libpcre3-dev

install:
  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check

  # Does the role work?
  - ansible-playbook tests/test.yml -i tests/inventory --connection=local --sudo

  # Idempotency check
  - >
    ansible-playbook tests/test.yml -i tests/inventory --connection=local --sudo
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
