# The postinst triggers of these packages reload/restart apache
# and php-fpm themselves (php7.0-xx restarts php7.0-fpm, php5-xx
# restarts php5-fpm etc.)
# Therefore we need no additional restart handler
- name: Install php ({{ php_package_prefix }})
  apt: pkg={{ php_package_prefix }}-{{ item }} state=present
  with_items: "{{ php_packages }}"
  when: php_version | version_compare('7.2', '<') or item != 'mcrypt'

- import_tasks: packages/zip.yml
  when: "'zip' in php_packages"

- import_tasks: packages/mbstring.yml
  when: "'mbstring' in php_packages"

- import_tasks: packages/xml.yml
  when: "'xml' in php_packages"

- import_tasks: packages/intl.yml
  when: "'intl' in php_packages"
