# The postinst triggers of these packages reload/restart apache
# and php-fpm themselves (php7.0-xx restarts php7.0-fpm, php5-xx
# restarts php5-fpm etc.)
# Therefore we need no additional restart handler
- name: Install php ({{ php_package_prefix }})
  apt: pkg={{ php_package_prefix }}-{{ item }} state=present
  with_items:
    - "cli"
    - "mysql"
    - "sqlite*" #php5-sqlite, but php7.0-sqlite3
    - "fpm"
    - "readline"
    - "curl"
    - "json"
    - "intl" # (required for Collator class)
    - "gd" # (required for piwik email reports)
    - "tidy" # (currently required for intranets)
    - "mcrypt"
    - "imap" # required for postfixadmin
    - "zip" # zip_open()
    - "mbstring" # mb_strlen() etc.
    - "xml" # required for roundcube
  when: php_package_prefix != 'php5' or item not in ['zip', 'mbstring', 'xml']

- name: Check zip extension
  command: >
    {{ php_package_prefix }} -r "zip_open('test');"
  changed_when: False

- name: Check mbstring extension
  command: >
    {{ php_package_prefix }} -r "mb_strlen('test');"
  changed_when: False

- name: Check xml extension
  command: >
    {{ php_package_prefix }} -r "new DomDocument();"
  changed_when: False

- name: Check intl extension
  command: >
    {{ php_package_prefix }} -r "collator_create('de_DE');"
  changed_when: False
