- name: Install php ({{ php_package_prefix }})
  apt: pkg={{ php_package_prefix }}-{{ item }} state=present
  with_items: "{{ php_packages_batch }}"
  when: php_version is version('8.0', '<') or item != 'json'

# By default, systemd throws an error when a service is restarted more than 5 times in 10 seconds
# As each php module install restarts php-fpm, we reset the counter to prevent this error
- name: Reset restart counter
  shell: systemctl reset-failed php{{ php_version}}-fpm
  changed_when: false
